from enum import Enum

Tipo = Enum(
    "Tipo",
    [
        # Single-character tokens.
        "PAR_IZQ",
        "PAR_DER",
        "LLAVE_IZQ",
        "LLAVE_DER",
        "COMA",
        "PUNTO",
        "PUNTO_Y_COMA",
        "NUMERAL",
        # One or two character tokens.
        "NEGACION",
        "NO_IGUAL",
        "ASIGNAR",
        "IGUAL_IGUAL",
        "MAYOR",
        "MAYOR_IGUAL",
        "MENOR",
        "MENOR_IGUAL",
        "MODULO",
        "MODULO_ASIGNAR",
        "MENOS",
        "MENOS_ASIGNAR",
        "MAS",
        "MAS_ASIGNAR",
        "BARRA",
        "DIV_ASIGNAR",
        "ESTRELLA",
        "ESTRELLA_ASIGNAR",
        # Literals.
        "IDENTIFICADOR",
        "CADENA",
        "NUMERO",
        # Keywords.
        "Y",
        "CLASE",
        "SINO",
        "FALSO",
        "DEFINICION",
        "DESDE",
        "SI",
        "NULO",
        "O",
        "IMPRIMIR",
        "RETORNAR",
        "PADRE",
        "ESTE",
        "CIERTO",
        "SEA",
        "MIENTRAS",
        "FIN",
    ],
)
